# CI Build number is incremental and not related to actual version number of the product
version: '{build}'

init:
  - git config --global core.autocrlf true

install:
  # Download install script to install .NET cli in .dotnet dir
  - ps: mkdir -Force ".\scripts\obtain\" | Out-Null
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/release/2.0.0/scripts/obtain/dotnet-install.ps1" -OutFile ".\scripts\obtain\dotnet-install.ps1"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - ps: '& .\scripts\obtain\dotnet-install.ps1 -InstallDir "$env:DOTNET_INSTALL_DIR" -NoPath'
  # add dotnet to PATH
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq $true) { $BuildNumber = "" } else { $BuildNumber = "build$env:APPVEYOR_BUILD_NUMBER" }
  - ps: Import-Module .\tools\psake\psake.psm1
  - ps: Invoke-psake .\build-definition.ps1 -properties @{ BuildNumber=$BuildNumber }
  - ps: if ($psake.build_success -eq $false) { exit 1 }

test: off

artifacts:
  - path: artifacts\nuget\**\*.nupkg
    name: NugetPackage

deploy:
  # publish all changes on master to MyGet
  - provider: Environment
    name: MyGet C3-OSS

  # new release tag -> create GitHub release
  - provider: GitHub
    release: $(appveyor_repo_tag_name)
    description: "See milestone for release notes"
    draft: true
    prerelease: true
    auth_token:
      secure: JU9H+A+WwAtz4Xkcd/50N239EiX1o7OpEnmtiQGayR+Zc2ZHF8xrcPMRelHyJwZL
    on:
      appveyor_repo_tag: true
