# CI Build number is incremental and not related to actual version number of the product
version: '{build}'

image: Visual Studio 2017 Preview

init:
  - git config --global core.autocrlf true

build_script:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq $true) { $BuildNumber = "" } else { $BuildNumber = "build$env:APPVEYOR_BUILD_NUMBER" }
  - ps: Import-Module .\tools\psake\psake.psm1
  - ps: Invoke-psake .\build-definition.ps1 -properties @{ BuildNumber=$BuildNumber }
  - ps: if ($psake.build_success -eq $false) { exit 1 }

test: off

artifacts:
  - path: artifacts\nuget\**\*.nupkg
    name: NugetPackage

deploy:
  # publish all changes on master to MyGet
  - provider: Environment
    name: MyGet C3-OSS
    on:
      branch: master

  # new release tag -> create GitHub release
  - provider: GitHub
    release: $(appveyor_repo_tag_name)
    description: "See milestone for release notes"
    draft: true
    prerelease: true
    auth_token:
      secure: pDFq6hq7aN0Ro6nLy1Q9457sLs8m86yGiai1lkbyaHT0I+Fgt4JCYagDmzPT1sSx
    on:
      appveyor_repo_tag: true
